export default {
  name: "textShort",
  title: "Short text",
  description: "Headings, Titles, Labels, Etc...",
  type: "object",
  fields: [
    {
      name: "shortTextContent",
      title: "Short Text Content",
      description: "Used for short form text",
      type: "string",
    },
    {
      name: "shortTextStyle",
      title: "Short Text Style",
      description: "Selected style for short form text",
      type: "string",
      options: {
        layout: "dropdown",
        list: [
          { title: "Heading", value: "head" },
          { title: "Subheading", value: "subhead" },
          { title: "Floater", value: "float" },
          { title: "Body", value: "body" },
        ],
      },
      hidden: ({ parent }) => parent?.shortTextContent === undefined,
      // validation: (Rule) => Rule.required(),
    },
    // {
    //   name: "shortTextFontSize",
    //   title: "Short Text Font Size",
    //   description: "Selected font size for short form text",
    //   type: "string",
    //   options: {
    //     layout: "dropdown",
    //     list: [
    //       { title: "8xl", value: "text-8xl" },
    //       { title: "7xl", value: "text-7xl" },
    //       { title: "6xl", value: "text-6xl" },
    //       { title: "5xl", value: "text-5xl" },
    //       { title: "4xl", value: "text-4xl" },
    //       { title: "3xl", value: "text-3xl" },
    //       { title: "2xl", value: "text-2xl" },
    //       { title: "xl", value: "text-xl" },
    //       { title: "lg", value: "text-lg" },
    //       { title: "base", value: "text-base" },
    //       { title: "sm", value: "text-sm" },
    //       { title: "xs", value: "text-xs" },
    //     ],
    //   },
    //   hidden: ({ parent }) => parent?.shortTextContent === undefined,
    //   // validation: (Rule) => Rule.required(),
    // },
    {
      name: "shortTextFontColor",
      title: "Short Text Font Color",
      description: "Font color for short form text",
      type: "string",
      options: {
        layout: "dropdown",
        list: [
          { title: "White", value: "white" },
          { title: "Black", value: "black" },
          { title: "Red", value: "red" },
        ],
      },
      hidden: ({ parent }) => parent?.shortTextContent === undefined,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: "shortTextAlign",
      title: "Short Text Alignment",
      description: "Positioning for short form text",
      type: "string",
      options: {
        layout: "dropdown",
        list: [
          { title: "Left", value: "left" },
          { title: "Center", value: "center" },
          { title: "Right", value: "right" },
          { title: "Justify", value: "justify" },
        ],
      },
      hidden: ({ parent }) => parent?.shortTextContent === undefined,
      // validation: (Rule) => Rule.required(),
    },
    {
      name: "shortTextBackground",
      title: "Short Text Background",
      type: "boolean",
    },
    {
      name: "shortTextBgColor",
      title: "Short Text Background Color",
      description: "Positioning for short form text",
      type: "string",
      options: {
        layout: "dropdown",
        list: [
          { title: "White", value: "white" },
          { title: "Black", value: "black" },
          { title: "Red", value: "red" },
        ],
      },
      hidden: ({ parent }) => parent?.shortTextBackground === false || parent?.shortTextBackground === undefined ,
      // validation: (Rule) => Rule.required(),
    },
  ],
};
